-- Week 10 PostgreSQL disclosure queries.
-- Run after schema_postgresql_week10.sql and import_week10_tables.sql.
\set ON_ERROR_STOP on
SET client_encoding = 'UTF8';

\copy (SELECT * FROM (SELECT 'company_research_panel_week10' AS table_name, COUNT(*)::int AS row_count FROM company_research_panel_week10 UNION ALL SELECT 'investor_profile_week10', COUNT(*)::int FROM investor_profile_week10 UNION ALL SELECT 'fund_enrichment_queue_week10', COUNT(*)::int FROM fund_enrichment_queue_week10 UNION ALL SELECT 'descriptive_stats_week10', COUNT(*)::int FROM descriptive_stats_week10 UNION ALL SELECT 'board_stats_week10', COUNT(*)::int FROM board_stats_week10 UNION ALL SELECT 'correlation_matrix_week10', COUNT(*)::int FROM correlation_matrix_week10 UNION ALL SELECT 'regression_results_week10', COUNT(*)::int FROM regression_results_week10 UNION ALL SELECT 'research_questions_week10', COUNT(*)::int FROM research_questions_week10 UNION ALL SELECT 'data_quality_gate_week10', COUNT(*)::int FROM data_quality_gate_week10 UNION ALL SELECT 'field_completeness_week10', COUNT(*)::int FROM field_completeness_week10) AS counts ORDER BY table_name) TO 'database/postgresql_table_counts_week10.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8');

\copy (SELECT stock_code, company_short, market, broad_pevc_record_share, pevc_strength_index, top1_ratio_pct, effective_shareholder_count, quality_gate FROM company_research_panel_week10 ORDER BY stock_code) TO 'database/postgresql_company_panel_disclosure_week10.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8');

\copy (SELECT market, company_count, avg_pevc_strength_index, avg_broad_pevc_record_share, avg_top1_ratio_pct, avg_effective_shareholder_count, caution_company_count FROM board_stats_week10 ORDER BY market) TO 'database/postgresql_board_summary_week10.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8');

\copy (SELECT investor_type_final, COUNT(*)::int AS investor_profile_rows, COALESCE(SUM(record_count), 0)::int AS source_record_count, COALESCE(SUM(company_count), 0)::int AS company_mentions, COALESCE(SUM(is_broad_pevc), 0)::int AS broad_pevc_profiles, COALESCE(SUM(is_fund_like_name), 0)::int AS fund_like_profiles FROM investor_profile_week10 GROUP BY investor_type_final ORDER BY investor_profile_rows DESC, investor_type_final) TO 'database/postgresql_investor_type_summary_week10.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8');

\copy (SELECT manual_priority, COUNT(*)::int AS fund_queue_rows, COUNT(NULLIF(amac_record_code, ''))::int AS amac_code_filled, COUNT(NULLIF(gp_name, ''))::int AS gp_filled, COUNT(NULLIF(lp_structure, ''))::int AS lp_structure_filled, MIN(disclosure_status) AS disclosure_status FROM fund_enrichment_queue_week10 GROUP BY manual_priority ORDER BY manual_priority) TO 'database/postgresql_fund_enrichment_status_week10.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8');

\copy (SELECT model_id, sample_scope, dependent_variable, independent_variable, n, coef_x, r_squared, model_note FROM regression_results_week10 ORDER BY model_id) TO 'database/postgresql_regression_brief_week10.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8');

\copy (SELECT * FROM (SELECT '数据库类型' AS item, 'PostgreSQL临时实例' AS value, '使用本机PostgreSQL 18工具链，在55432端口独立启动，不依赖5432主库口令' AS source_note UNION ALL SELECT '当前数据库', current_database(), 'psql查询current_database()所得' UNION ALL SELECT '当前用户', current_user, 'psql查询current_user所得' UNION ALL SELECT '监听端口', current_setting('port'), '由run_postgres_temp_week10.ps1指定' UNION ALL SELECT '导入表数量', (SELECT COUNT(*)::text FROM information_schema.tables WHERE table_schema = 'public'), '从information_schema.tables统计public schema中的本周表' UNION ALL SELECT '导入总行数', ((SELECT COUNT(*) FROM company_research_panel_week10) + (SELECT COUNT(*) FROM investor_profile_week10) + (SELECT COUNT(*) FROM fund_enrichment_queue_week10) + (SELECT COUNT(*) FROM descriptive_stats_week10) + (SELECT COUNT(*) FROM board_stats_week10) + (SELECT COUNT(*) FROM correlation_matrix_week10) + (SELECT COUNT(*) FROM regression_results_week10) + (SELECT COUNT(*) FROM research_questions_week10) + (SELECT COUNT(*) FROM data_quality_gate_week10) + (SELECT COUNT(*) FROM field_completeness_week10))::text, '10张结果表合计行数' UNION ALL SELECT '公司样本数', (SELECT COUNT(*)::text FROM company_research_panel_week10), 'company_research_panel_week10' UNION ALL SELECT '投资主体画像数', (SELECT COUNT(*)::text FROM investor_profile_week10), 'investor_profile_week10' UNION ALL SELECT '基金核验队列数', (SELECT COUNT(*)::text FROM fund_enrichment_queue_week10), 'fund_enrichment_queue_week10' UNION ALL SELECT '备案编码/GP/LP已披露记录', (SELECT COUNT(*)::text FROM fund_enrichment_queue_week10 WHERE NULLIF(amac_record_code, '') IS NOT NULL OR NULLIF(gp_name, '') IS NOT NULL OR NULLIF(lp_structure, '') IS NOT NULL), '三表未直接披露则保持空值，不用名称推断' UNION ALL SELECT '主库5432状态', '服务可用但需要口令', '已用psql -w测试，默认postgres用户返回no password supplied') AS summary) TO 'database/postgresql_disclosure_summary_week10.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8');
