-- Week 12 PostgreSQL schema. Generated by code/week12_expansion_pipeline.py.
SET client_min_messages TO warning;
CREATE SCHEMA IF NOT EXISTS pevc_week12;
SET search_path TO pevc_week12;

DROP TABLE IF EXISTS "week12_source_catalog";
CREATE TABLE "week12_source_catalog" (
    "source_id" text,
    "source_name" text,
    "source_type" text,
    "local_path" text,
    "records_available" text,
    "usable_records" text,
    "fields_provided" text,
    "week12_usage" text,
    "source_limitation" text
);

DROP TABLE IF EXISTS "week12_source_inventory";
CREATE TABLE "week12_source_inventory" (
    "company_key" text,
    "source_group" text,
    "sample_id" text,
    "stock_code" text,
    "company_name" text,
    "company_short" text,
    "exchange" text,
    "board" text,
    "listing_date" text,
    "ipo_year" text,
    "prospectus_date" text,
    "source_platform" text,
    "source_page_url" text,
    "prospectus_url" text,
    "local_pdf_path" text,
    "local_text_path" text,
    "source_status" text,
    "source_level" text,
    "page_count" text,
    "file_size_mb" text,
    "keyword_hit_count" text,
    "keyword_hit_summary" text,
    "week12_role" text,
    "recommended_action" text
);

DROP TABLE IF EXISTS "week12_expanded_company_universe";
CREATE TABLE "week12_expanded_company_universe" (
    "company_key" text,
    "source_group" text,
    "sample_id" text,
    "stock_code" text,
    "company_name" text,
    "company_short" text,
    "exchange" text,
    "board" text,
    "listing_date" text,
    "ipo_year" text,
    "prospectus_date" text,
    "source_platform" text,
    "source_page_url" text,
    "prospectus_url" text,
    "local_pdf_path" text,
    "local_text_path" text,
    "source_status" text,
    "source_level" text,
    "page_count" text,
    "file_size_mb" text,
    "keyword_hit_count" text,
    "keyword_hit_summary" text,
    "week12_role" text,
    "recommended_action" text
);

DROP TABLE IF EXISTS "week12_processing_queue";
CREATE TABLE "week12_processing_queue" (
    "queue_id" text,
    "priority" text,
    "stock_code" text,
    "company_short" text,
    "company_name" text,
    "board" text,
    "exchange" text,
    "source_group" text,
    "source_platform" text,
    "source_url" text,
    "local_pdf_path" text,
    "local_text_path" text,
    "page_count" text,
    "file_size_mb" text,
    "keyword_hit_count" text,
    "keyword_hit_summary" text,
    "week12_action" text,
    "expected_output" text,
    "missing_policy" text
);

DROP TABLE IF EXISTS "week12_source_summary";
CREATE TABLE "week12_source_summary" (
    "source_group" text,
    "universe_company_count" text,
    "week12_queue_count" text,
    "with_url_count" text,
    "with_local_pdf_count" text,
    "with_local_text_count" text,
    "note" text
);

DROP TABLE IF EXISTS "week12_board_coverage_summary";
CREATE TABLE "week12_board_coverage_summary" (
    "board" text,
    "universe_company_count" text,
    "week12_queue_count" text,
    "url_coverage_count" text,
    "local_pdf_count" text,
    "local_text_count" text,
    "week12_position" text
);

DROP TABLE IF EXISTS "week12_field_source_matrix";
CREATE TABLE "week12_field_source_matrix" (
    "field_group" text,
    "field_name" text,
    "primary_source" text,
    "source_evidence" text,
    "auto_method" text,
    "manual_check" text,
    "missing_rule" text
);

DROP TABLE IF EXISTS "week12_weekly_plan";
CREATE TABLE "week12_weekly_plan" (
    "day" text,
    "focus" text,
    "action" text,
    "expected_output" text,
    "acceptance" text
);

DROP TABLE IF EXISTS "week12_scaling_protocol";
CREATE TABLE "week12_scaling_protocol" (
    "step_no" text,
    "stage" text,
    "input" text,
    "method" text,
    "output" text,
    "risk_control" text
);

DROP TABLE IF EXISTS "week12_quality_gates";
CREATE TABLE "week12_quality_gates" (
    "gate_id" text,
    "gate" text,
    "rule" text,
    "failure_action" text
);

DROP TABLE IF EXISTS "week12_database_load_plan";
CREATE TABLE "week12_database_load_plan" (
    "table_name" text,
    "row_count" text,
    "source_csv" text,
    "database_schema" text,
    "load_status" text,
    "use_case" text
);

DROP TABLE IF EXISTS "week12_submission_checklist";
CREATE TABLE "week12_submission_checklist" (
    "item" text,
    "status" text,
    "evidence" text
);

