-- Week 11 PostgreSQL schema. Generated by code/week11_pipeline.py.
SET client_min_messages TO warning;
CREATE SCHEMA IF NOT EXISTS pevc_week11;
SET search_path TO pevc_week11;

DROP TABLE IF EXISTS "week11_database_migration_plan";
CREATE TABLE "week11_database_migration_plan" (
    "step_id" text,
    "task" text,
    "status" text,
    "evidence" text,
    "remaining_risk" text,
    "next_action" text
);

DROP TABLE IF EXISTS "week11_persistent_db_readiness";
CREATE TABLE "week11_persistent_db_readiness" (
    "check_item" text,
    "result" text,
    "detail" text,
    "action" text
);

DROP TABLE IF EXISTS "week11_fund_deep_enrichment_queue";
CREATE TABLE "week11_fund_deep_enrichment_queue" (
    "record_id" text,
    "investor_name" text,
    "investor_type_final" text,
    "investor_type_basis" text,
    "stock_code" text,
    "company_short" text,
    "market" text,
    "manual_priority" text,
    "source_tables" text,
    "pdf_pages_observed" text,
    "amac_record_code" text,
    "gp_name" text,
    "lp_structure" text,
    "pdf_direct_disclosure" text,
    "needs_amac_check" text,
    "needs_gp_lp_check" text,
    "verification_priority" text,
    "source_priority" text,
    "week11_status" text,
    "manual_instruction" text,
    "engineering_rule" text
);

DROP TABLE IF EXISTS "week11_manual_verification_template";
CREATE TABLE "week11_manual_verification_template" (
    "record_id" text,
    "stock_code" text,
    "company_short" text,
    "investor_name" text,
    "investor_type_final" text,
    "verify_item" text,
    "current_value" text,
    "evidence_location" text,
    "manual_rule" text,
    "suggested_action" text,
    "check_result" text,
    "reviewer" text,
    "update_target" text
);

DROP TABLE IF EXISTS "week11_research_design_matrix";
CREATE TABLE "week11_research_design_matrix" (
    "question_id" text,
    "research_question" text,
    "dependent_variable" text,
    "key_explanatory_variable" text,
    "controls" text,
    "sample_scope" text,
    "method" text,
    "current_limit" text,
    "week11_output" text
);

DROP TABLE IF EXISTS "week11_variable_dictionary";
CREATE TABLE "week11_variable_dictionary" (
    "variable" text,
    "cn_name" text,
    "table" text,
    "type" text,
    "definition" text,
    "derivation" text
);

DROP TABLE IF EXISTS "week11_sample_expansion_plan";
CREATE TABLE "week11_sample_expansion_plan" (
    "plan_id" text,
    "period" text,
    "scope" text,
    "target" text,
    "success_criteria" text,
    "status" text
);

DROP TABLE IF EXISTS "week11_quality_dashboard";
CREATE TABLE "week11_quality_dashboard" (
    "metric" text,
    "value" text,
    "interpretation" text
);

DROP TABLE IF EXISTS "week11_completion_checklist";
CREATE TABLE "week11_completion_checklist" (
    "item" text,
    "status" text,
    "evidence" text
);

DROP TABLE IF EXISTS "week11_manifest";
CREATE TABLE "week11_manifest" (
    "file" text,
    "rows" text,
    "role" text,
    "source" text
);

